### ISSUE TITLE
Error in android folders path in project with VGV CLI

### ISSUE THREAD

**Issue by alejandrogiubel** [atiqsamtia/change_app_package_name#18]
Hi great plugin. In VGV CLI created project the plugins can't find the MainActivity path, for Kotlin or java. The app package name change ok (in AndroidManifest) but the directory structure (MainActivity path) and the import in MainActivity not change. Thanks

**Comment by atiqsamtia** [comment]
Hi @alejandrogiubel can you share the project structure in VGV CLI created project? so I could add support for that

**Comment by alejandrogiubel** [comment]
MainActivity path
![Captura de Pantalla 2022-05-29 a la(s) 10 38 31](https://user-images.githubusercontent.com/36578847/170875016-a594af87-84a3-45d0-abe9-0ddba0dbf500.png)

![Captura de Pantalla 2022-05-29 a la(s) 10 47 54](https://user-images.githubusercontent.com/36578847/170875523-06c1d1b3-5640-4fae-9fa0-6b687a322470.png)


MainActivity file
![Captura de Pantalla 2022-05-29 a la(s) 10 42 06](https://user-images.githubusercontent.com/36578847/170875227-01609ef6-9f6d-47f5-bfbf-9b72c6b66a4c.png)


Console error
![Captura de Pantalla 2022-05-29 a la(s) 10 41 26](https://user-images.githubusercontent.com/36578847/170875191-256a1b2e-504e-4217-b148-1eaa31fb1c60.png)

**Comment by atiqsamtia** [comment]
The issue is with VGV CLI.

Let's say your app directory is `demo`
It puts package name as `com.example.verygoodcore.demo`

but it generates directory structure as `com/example/verygoodcore` thus omitting the app directory here. 

I'm adding an additional check here to mitigate this but you should raise this issue with https://github.com/VeryGoodOpenSource/very_good_cli/ as well

Fix is already live

**Comment by alejandrogiubel** [comment]
You are right. VGV CLI generates another project structure different from the common one, but since it is a widely used CLI, I think the correction is valid. Thanks for your quick response. Everything works as expected. 👍🏼
