### ISSUE TITLE
google-services.json not updated - Causes Execution failed for task ':app:processDebugGoogleServices' error

### ISSUE THREAD

**Issue by samanson123** [atiqsamtia/change_app_package_name#40]
A common extra file that is added on the Android side of Flutter is the google-services.json file for some Firebase and Flutterfire related functionality. This file has a manual reference to the Android package name. Running the change package name command does not update the reference in this file.

While it is a relatively easy manual fix, it would be handy if it also checked this file and updated the reference in this file if it exists considering how widely used Firebase is.

**Comment by atiqsamtia** [comment]
I considered this but the issue is updating the package name in google-services.json file is not enough as the app with new package name needs to be registered with Firebase to work well. The better solution is to use FlutterFire CLI and it takes care of updating the file for you. You can run `flutterfire reconfigure` command and it's enough

Hope this helps with your usecase
